name: clonify
description: A powerful CLI tool for managing multiple Flutter project clones with different configurations, branding, and Firebase projects. Perfect for white-label apps.
version: 0.3.1
homepage: https://github.com/DevMohammadSalameh/clonify
repository: https://github.com/DevMohammadSalameh/clonify
issue_tracker: https://github.com/DevMohammadSalameh/clonify/issues
license: GPL-3.0-or-later

topics:
  - cli
  - flutter
  - white-label
  - multi-tenant
  - clone

environment:
  sdk: ^3.8.1

platforms:
  linux:
  macos:
  windows:

dependencies:
  args: ^2.3.0
  logger: ^2.0.2+1
  path: ^1.8.0
  yaml_edit: ^2.2.2
  yaml: ^3.1.3
  process: ^5.0.0


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

executables:
  clonify:
